### PR TITLE
Style search bar

### PR DESCRIPTION
**Pull request by Steve0Greatness**
Style the search bar at the top of the page, this uses another variable just called search-bar to determine what the color of the text and border of the search bar should be, and uses the header color for the color of the background, this could 100% use some improvement.

### CODE REVIEW

**Comment by stickfiregames** [comment]
Please could you add GitHub Pages to your fork, so we can preview your changes?

**Comment by stickfiregames** [comment]
[I also tried changing the buttons and text boxes](https://stickfiregames.github.io/forumoji/) based how the links in the top right look at the moment, but I also think it needs improvement so I haven't submitted it yet .

**Comment by Steve0Greatness** [comment]
As requested, I'm adding GH pages, it should be up at https://steve0greatness.github.io/forumoji/ soon. It's currently deploying.

**Comment by Steve0Greatness** [comment]
> [I also tried changing the buttons and text boxes](https://stickfiregames.github.io/forumoji/) based how the links in the top right look at the moment, but I also think it needs improvement so I haven't submitted it yet .

I think you should make it so that when the copy button or the bbcode textbox are focused, they should add an outline to each other as well. This can be done with the selectors `#bbcode:focus + #copyBbcode` and `#bbcode:has(+ #copyBbcode:focus)`, at least in theory.

**Pull request closed without merging**
