### PR TITLE
Neutral Style Update

### PR DESCRIPTION
**Pull request by Steve0Greatness**
The neutral style looks really bad. I know it will only be seen if the user has JS turned off, but still.

### CODE REVIEW

**Comment by lopste** [comment]
If it can only be seen with JS turned off, what's the point? This website requires JS.

**Comment by Steve0Greatness** [comment]
> If it can only be seen with JS turned off, what's the point? This website requires JS.

Why even have it if it's only seen with JS turned on? There's a `default` theme anyways.

**Comment by lopste** [comment]
>
> If it can only be seen with JS turned off, what's the point? This website
> requires JS.
>
> Why even have it if it's only seen with JS turned on? There's a default
> theme anyways.
>
That’s for people who don’t want eye strain. Having a non-JS theme defeats
the point of a website with JS.

>

**Comment by stickfiregames** [comment]
The reason for the neutral style is so that it's less noticeable when it flashes for a split second before the user's style loads.

Though if we're going to have a message for non JS users, it would help if it's at least readable.

**Pull request closed without merging**
